name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libegl1 libxslt1.1 libxkbfile1 xvfb
      - name: Install Python deps
        run: |
          pip install uv
          uv sync
          uv pip install -e .
      - name: Run tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          export DISPLAY=:99
          xvfb-run -a uv run -m pytest -q
